name:                gah
version:             0.2.0
synopsis:            A simple Github Actions cli for the flumoxed developer.
github:              dogonthehorizon/gah
license:             MIT
author:              Fernando Freire
maintainer:          Fernando Frerei <dogonthehorizon@gmail.com>
copyright:           2020 Fernando Freire
category:            CLI

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell


dependencies:
  - base >= 4.7 && < 5
  - mtl
  - text

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - bytestring
    - conduit
    - conduit-extra
    - lens
    - modern-uri
    - req
    - req-conduit
    - text-show
    - unordered-containers
    - zip-stream

flags:
  static:
    description: Build a static binary.
    manual: true
    default: false

executables:
  gah:
    source-dirs:      app
    main:             Main.hs
    dependencies:
      - gah
      - envy
      - optparse-applicative
    when:
      - condition: flag(static)
        ghc-options:
          - -threaded
          - -static
          - -O2
          - -optl-static
          - -optl-pthread
          - -fPIC
        cc-options: -static
        ld-options: -static -pthread
